leipzig_columns_dict = {'Age': 'Age_cln',
                        'YGTSS_Total_Tic_Score': 'ygtss_total_tic_score',
                        'YGTSS_Motoric_Score': 'ygtss_motor_score',
                        'YGTSS_Vocal_Score': 'ygtss_vocal_score',
                        'YGTSS_Total_Score_incl_Impairment': 'ygtss_global_score',
                        'RVTRS': 'rvtrs_score',
                        'DSM4_ADHD_Score': 'dsm4_adhd_score',
                        'DSM4_Attention': 'dsm4_attention_score',
                        'DSM4_Hyperactivity': 'dsm4_hyperactivity_score',
                        'DSM4_clinically_significant_ADHD': 'dsm4_adhd_sig',
                        'CAARS_Score_ADHS_Symptoms_Total_Cat_G_T_Score': 'caars_adhd_score',
                        'OCIR_Wash': 'ocir_wash',
                        'OCIR_Thoughts': 'ocir_thoughts',
                        'OCIR_Hoarding': 'ocir_hoarding',
                        'OCIR_Tidy': 'ocir_tidy',
                        'OCIR_Mental_Neutralisation': 'ocir_mental_neutralisation',
                        'OCIR_Control': 'ocir_control',
                        'OCIR_total score': 'ocir_total_score',
                        # 'OCIR_WASH_clinically_significant'                : 'ocir_wash_sig',
                        # 'OCIR_Thoughts_clinically_significant'            : 'ocir_thoughts_sig',
                        # 'OCIR_Hoarding_clinically_significant'            : 'ocir_hoarding_sig',
                        # 'OCIR_Tidy_clinically_significant'                : 'ocir_tidy_sign',
                        # 'OCIR_Mental_Neutralisation_clinically_significant':'ocir_mental_neutralisation_sig',
                        # 'OCIR_Control_clinically_significant'             : 'ocir_control_sig',
                        'YBOCS_obsessions': 'ybocs_obsessions',
                        'YBOCS_obsessions_sig': 'ybocs_obsessions_sig',
                        'YBOCS_compulsions': 'ybocs_compulsions',
                        'YBOCS_compulsions_sig': 'ybocs_compulsions_sig',
                        'YBOCS_Totalscore_Items_1to10': 'ybocs_total_score',
                        'YBOCS_Totalscore_Items_1to10_clinically_significant': 'ybocs_total_score_sig',
                        'BDI12': 'bdi_score',
                        'BDI12_clinically_significant': 'bdi_clinical_significance',
                        'BDI12_severity': 'bdi_severity',
                        'MADRS': 'madrs_score',
                        'MADRS_clinically_significant': 'madrs_sig',
                        'MADRS_severity': 'madrs_severity',
                        'BAI': 'bai_score',
                        'BAI_clinically_significant': 'bai_sig',
                        'BAI_severity': 'bai_severity',
                        'puts': 'puts_score',
                        'puts_meaning': 'puts_meaning',
                        'qol_score': 'qol_score',
                        'qol_scale': 'qol_scale',
                        'qol_clinical meaning': 'qol_meaning',
                        'Ferritin': 'ferritin_a',
                        'Ferritin_B': 'ferritin_b',
                        'Diag_ADHD': 'diagnosis_adhd',
                        'Diag_OCD': 'diagnosis_ocd',
                        'Diag_Depression': 'diagnosis_depression',
                        'Diag_Anxiety': 'diagnosis_anxiety',
                        'Diag_AQ': 'diagnosis_autism',
                        'medication': 'medication',
                        'medication_history_type': 'medication_history_type',
                        # 'THC_occasional'                                  : 'thc_occasional',
                        'group_id': 'group_id'
                        }



hamburg_columns_dict = {'Group_id'                         : 'group_id',
                        'GENDER'                           : 'Sex',
                        'AGE_STUDY'                        : 'Age',
                        #'Bildung in Jahren'                : 'education',
                        #'Beruf'                            : 'occuapation',
                        #'Raucher'                          : 'smoking',
                        #'Wieviel'                          : 'smoking_freq',
                        #'Brille'                           : 'glassess',
                        #'starke'                           : 'glassess_strength',
                        #'Hirntrauma'                       : 'brain_trauma',
                        #'Vorerkrankungen'                  : 'pre_existing_conditions',
                        'Medikation heute'                 : 'medication',
                        'Welche'                           : 'medication_type',
                        'Medikation'                       : 'medication_history',
                        'Medikation fuher'                 : 'medication_history_type',
                        'Alter bei Symptombeginn'          : 'symptom_age_onset',
                        'Symtome seit Jahren'              : 'symptom_n_years',
                        'Alter bei Diagnose-Stellung'      : 'symptom_age_diagnosis',
                        'Intervall zw Symptombeginn und Diagnose': 'symptom_interval_onset_diag',
                        'Familienanamnese'                 : 'symptom_family_history',
                        #'Diagnostic Confidence Index'      : 'diagnostic_confidence_index',
                        'YGTSS_50'                         : 'ygtss_total_score',
                        #'Gesamtbeeintr_chtigung '          : 'ygtss_impairment_score',
                        'YGTSS TOTAL'                      : 'ygtss_global_score',
                        'RUSH alone'                       : 'rvtrs_score',
                        'Dranggefuhl'                      : 'urge_to_tic',
                        'PUTS fur Kinder'                  : 'puts_score',
                        'GTS _ Quality of Life'            : 'qol_score',
                        'Satisfaction'                     : 'qol_satisfaction',
                        'Beck-Depressions-Inventar'        : 'beck_score',
                        'Verdacht auf Depression'          : 'diagnosis_depression',
                        'diagnosis'                        : 'diagnosis'
                        }



hannover_b_columns_dict= {
                        #'Untersuchung_1'                     : 'ScanDate_1',
                        #'Untersuchung_2'                     : 'ScanDate_2',
                        #'Geschlecht'                         : 'Gender_cln',
                        #'Geburtsdatum'                       : 'DOB',
                        'Alter_Jahr'                         : 'Age_cln',
                        #'Neuroleptikum'                      : 'medication_neuroleptics',
                        #'Methylphenidat'                     : 'medication_methylphnidate',
                        #'SSRI'                               : 'medication_ssri',
                        #'NaSSA'                              : 'medication_nassa',
                        'medication'                         : 'medication',
                        'YGTSS mot. Ges.'                    : 'ygtss_motor_score',
                        'YGTSS vok. Ges. '                   : 'ygtss_vocal_score',
                        'YGTSS Tic-Score '                   : 'ygtss_total_tic_score',
                        'YGTSS Beeintrsschtigung '           : 'ygtss_impairment_score',
                        'YGTSS Ges. '                        : 'ygtss_global_score',
                        'Y-BOCS Gedanken '                   : 'ybocs_obsessions',
                        'Y-BOCS Handlungen '                 : 'ybocs_compulsions',
                        'Y-BOCS Ges. '                       : 'ybocs_total_score',
                        'Zwsnge aktuell ja/nein '            : 'Zwsnge aktuell ja/nein',
                        'BSI GSI '                           : 'bsi_gsi',
                        'BSI TGSI '                          : 'bsi_tgsi',
                        'BSI PST '                           : 'bsi_pst',
                        'BSI PSDI '                          : 'bsi_psdi',
                        'psychisch auffssllig belastet ja/nein' : 'psychisch auffssllig belastet ja/nein', #
                        'DSM-IV 1-9 '                        : 'dsm4_1_to_9',#
                        'DSM-IV 10-18 '                      : 'dsm4_10_to_18',#
                        'ADHS laut DSM-IV sig'               : 'dsm4_adhd_sig',
                        'Wenn ja, welcher Typus'             : 'dsm4_adhd_type',#
                        'Wurs-k ADHS ja/nein'                : 'wurs_adhd_sig',
                        'Wurs-k- Kontr.wert'                 : 'Wurs-k- Kontr.wert',#
                        'CARS: ADHS ja/nein'                 : 'caars_adhd_sig',
                        'AHDS laut Akte'                    :  'AHDS laut Akte',#
                        'Gesamt ADHS ja/nein'               :  'Gesamt ADHS ja/nein',#
                        'BDI Ges.score '                     : 'bdi_score',
                        'Depressionen ja/nein '              : 'diagnosis_depression',
                        'PUTS '                              : 'puts_score',
                        #'GTS-QOL Psychological d. '          :
                        #'GTS-QOL Physical and AODL d. '      : ''
                        #'GTS-QOL Obsessive-compulsive d. '   :
                        #'GTS-QOL Cognitive d. ':
                        'GTS-QOL gesamt '                    : 'qol_score',
                        #'GTS-QOL VAS ':
                        #'STAI-G X1 '                         : 'staig_x1',
                        #'STAI-G X2 '                         : 'staig_x2',
                        'Video Total Score'                  : 'rvtrs_score',
                        #'Video No. Of body areas'            : 'rvtrs_n_areas',
                        #'Video Motor tic frequency'          : 'rvtrs_motor_freq',
                        #'Video Phonic tic frequency'         : 'rvtrs_vocal_freq',
                        #'Video Severity of motor tics'       : 'rvtrs_motor_severity',
                        #'Video Severity of phonic tics'      : 'rvtrs_vocal_severity',
                        'group_id'                           : 'group_id'
                         }

